set_project("stx_tests")
set_version("2.0.0")
set_xmakever("2.9.0")

add_rules("mode.debug", "mode.release")

includes("..")

local stx_dir = path.join(os.scriptdir(), "..")

add_requires("catch2 v3.13.0")

target("stx-tests")
    set_default(true)
    set_languages("c++23")
    set_kind("binary")

    add_files("tests/*.cpp")

    add_includedirs(path.join(stx_dir, "include"))

    add_packages("catch2")

    on_config(function(target)
        import("core.project.config")
        local info = import("xmake.triple").get(target)
        if info.toolchain ~= "gcc" and info.toolchain ~= "clang" then
            cprint("${red}This project only supports GCC and Clang toolchains.")
            os.exit(1)
        end
    end)

    before_run(function(target)
        cprint("${green}[Running all tests...]")
    end)
target_end()

target("test-core")
    set_languages("c++23")
    set_kind("binary")
    add_files("tests/core.cpp")
    add_includedirs(path.join(stx_dir, "include"))
    add_packages("catch2")
    after_run(function(target)
        cprint("${green}[test-core passed]")
    end)
target_end()

target("test-mem")
    set_languages("c++23")
    set_kind("binary")
    add_files("tests/mem.cpp")
    add_includedirs(path.join(stx_dir, "include"))
    add_packages("catch2")
    after_run(function(target)
        cprint("${green}[test-mem passed]")
    end)
target_end()

target("test-fn")
    set_languages("c++23")
    set_kind("binary")
    add_files("tests/fn.cpp")
    add_includedirs(path.join(stx_dir, "include"))
    add_packages("catch2")
    after_run(function(target)
        cprint("${green}[test-fn passed]")
    end)
target_end()

target("test-range")
    set_languages("c++23")
    set_kind("binary")
    add_files("tests/range.cpp")
    add_includedirs(path.join(stx_dir, "include"))
    add_packages("catch2")
    after_run(function(target)
        cprint("${green}[test-range passed]")
    end)
target_end()

target("test-time")
    set_languages("c++23")
    set_kind("binary")
    add_files("tests/time.cpp")
    add_includedirs(path.join(stx_dir, "include"))
    add_packages("catch2")
    after_run(function(target)
        cprint("${green}[test-time passed]")
    end)
target_end()

target("test-fs")
    set_languages("c++23")
    set_kind("binary")
    add_files("tests/fs.cpp")
    add_includedirs(path.join(stx_dir, "include"))
    add_packages("catch2")
    after_run(function(target)
        cprint("${green}[test-fs passed]")
    end)
target_end()

target("test-dump")
    set_languages("c++23")
    set_kind("binary")
    add_files("tests/dump.cpp")
    add_includedirs(path.join(stx_dir, "include"))
    add_packages("catch2")
    after_run(function(target)
        cprint("${green}[test-dump passed]")
    end)
target_end()

target("run-all")
    set_kind("phony")
    add_deps("test-core", "test-mem", "test-fn", "test-range", "test-time", "test-fs", "test-dump")

    on_run(function(target)
        cprint("${yellow}[Running all tests in sequence...]")
    end)
target_end()
